### PR TITLE
Include licence metadata on watch page

### LINKED ISSUE #3: Include machine readable license metadata on Watch page
part of https://github.com/beeldengeluid/extending-peertube/issues/19

### PR DESCRIPTION
**Pull request by phivk**
include licence metadata on watch page by 
- inserting attributes to existing elements for Title and Author
- inserting new `link` tag for Work URL. 

closes #3 

@frankstrater I couldn't find a more robust way to find the Video Author element than querying for `'[title="Account page"]'`, which doesn't feel very future proof. Any ideas for less brittle ways to approach this?

### CODE REVIEW

**Review by frankstrater — COMMENTED** [review]
Please replace all insertAdjacentHTML() html injection with normal virtual DOM manipulation with createElement(). See example in the updated master.

**Comment by frankstrater** [comment]
> @frankstrater I couldn't find a more robust way to find the Video Author element than querying for `'[title="Account page"]'`, which doesn't feel very future proof. Any ideas for less brittle ways to approach this?

I'm looking into this for all HTML node selections. You could ask the PeerTube developers through https://framagit.org/framasoft/peertube/official-plugins/-/issues or via their chat room https://app.element.io/#/room/#peertube:matrix.org

Could you also merge the new master in this branch and adjust you code accordingly?

**Comment by phivk** [comment]
sure, I'll merge master into this branch and implement your feedback on top of that.

**Comment by phivk** [comment]
@frankstrater I just merged in master and noticed that the licence icon element is no longer inserted in the first `div.video-info-date-views` element that is displayed on narrow screens.

1E70E7BB-2AC2-4B65-84DE-4E335B08759B-500-00003DED61A139A8

I haven't yet found out why this is.
Could you have a look?

**Comment by frankstrater** [comment]
I noticed this as well. Can you make a separate issue for this, so we can fix this in another branch?

@phivk  EDIT; nevermind, already fixed it.

**Pull request merged**
